const swaggerJSDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const clc = require('cli-color');

const options = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'Your API',
            version: '1.0.0',
            description: 'A simple Express API with autogenerated Swagger documentation',
        },
        servers: [
            {
                url: 'http://localhost:5000',
            },
        ],
        components: {
            securitySchemes: {
                bearerAuth: {
                    type: 'http',
                    scheme: 'bearer',
                    bearerFormat: 'JWT',
                },
            },
        },
    },
    apis: ['./src/swagger/*.yaml', './src/controllers/*.js'], // Use specific file paths
};

const swaggerSpec = swaggerJSDoc(options);
const baseUrl = 'http://localhost:3030';

// Delay the console output by 3 seconds
setTimeout(() => {
    console.log(
        clc.red(`
  -----------------------------------------
  `)
    );
    console.log(clc.green.bold(`  Xtreme-Backend API Documentation is available at:`));
    console.log(clc.yellow(`  Mode: Development`));
    console.log(
        clc.cyan(`  Visit: ${clc.underline(baseUrl + '/api-docs')} to view the documentation`)
    );
    console.log(
        clc.red(`
  -----------------------------------------
  `)
    );
}, 3000);

const setupSwagger = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
};

module.exports = { setupSwagger };
